package com.ai2qa.domain.model;

/**
 * Status of the AI-generated summary for a test run.
 *
 * <p>Tracks the lifecycle of summary generation which happens
 * asynchronously after a test run completes. This allows the
 * frontend to show appropriate loading states.
 */
public enum SummaryStatus {
    /**
     * Summary generation has not started yet.
     * This is the initial state before the run completes.
     */
    PENDING,

    /**
     * Summary is currently being generated by AI.
     * Frontend should show a loading/generating indicator.
     */
    GENERATING,

    /**
     * Summary was successfully generated.
     * The summary field will contain the AI-generated content.
     */
    COMPLETED,

    /**
     * Summary generation failed (timeout, AI error, etc).
     * A fallback summary may be used instead.
     */
    FAILED;

    /**
     * Returns true if the summary is still being processed.
     */
    public boolean isInProgress() {
        return this == PENDING || this == GENERATING;
    }

    /**
     * Returns true if the summary processing is complete (success or failure).
     */
    public boolean isTerminal() {
        return this == COMPLETED || this == FAILED;
    }
}
